import React from 'react';
import { AnalysisResult, RiskLevel, EffortLevel } from '../types';
import { 
  ShieldAlert, 
  BrainCircuit, 
  Layers, 
  CheckSquare, 
  Rocket,
  Clock,
  AlertOctagon,
  Code,
  FileText,
  Printer,
  Download
} from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell, PieChart, Pie } from 'recharts';

interface AnalysisReportProps {
  result: AnalysisResult;
}

// Helper to determine colors
const getRiskColor = (level: RiskLevel) => {
  switch (level) {
    case RiskLevel.CRITICAL: return 'bg-red-100 text-red-800 border-red-200';
    case RiskLevel.HIGH: return 'bg-orange-100 text-orange-800 border-orange-200';
    case RiskLevel.MEDIUM: return 'bg-yellow-100 text-yellow-800 border-yellow-200';
    case RiskLevel.LOW: return 'bg-green-100 text-green-800 border-green-200';
    default: return 'bg-gray-100 text-gray-800';
  }
};

const getEffortColor = (level: EffortLevel) => {
  switch (level) {
    case EffortLevel.HIGH: return '#f97316'; // orange-500
    case EffortLevel.MEDIUM: return '#eab308'; // yellow-500
    case EffortLevel.LOW: return '#22c55e'; // green-500
    default: return '#94a3b8';
  }
};

export const AnalysisReport: React.FC<AnalysisReportProps> = ({ result }) => {
  
  // Data for Effort Chart
  const effortData = [
    { name: 'Low', value: result.effort === EffortLevel.LOW ? 100 : 30 },
    { name: 'Medium', value: result.effort === EffortLevel.MEDIUM ? 100 : 30 },
    { name: 'High', value: result.effort === EffortLevel.HIGH ? 100 : 30 },
  ];

  // Data for Risk Pie
  const riskValue = result.riskLevel === RiskLevel.CRITICAL ? 100 : result.riskLevel === RiskLevel.HIGH ? 75 : result.riskLevel === RiskLevel.MEDIUM ? 50 : 25;
  const riskData = [
    { name: 'Risk', value: riskValue },
    { name: 'Safety', value: 100 - riskValue },
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = () => {
    const element = document.getElementById('report-content');
    if (!element) return;

    // @ts-ignore
    if (window.html2pdf) {
      const opt = {
        margin: [10, 10], // top, left, bottom, right
        filename: `${result.projectTitle.replace(/\s+/g, '_')}_Analysis.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      };
      
      // @ts-ignore
      window.html2pdf().set(opt).from(element).save();
    } else {
      // Fallback to print if library fails to load
      window.print();
    }
  };

  const downloadMarkdown = () => {
    const {
      projectTitle,
      riskLevel,
      effort,
      understanding,
      functionalComplexity,
      nonFunctionalConstraints,
      riskJustification,
      highRiskModules,
      architectureRecommendation,
      techStack,
      automationStrategy,
      qualityGates,
      finalRecommendations,
      timestamp
    } = result;

    const date = new Date(timestamp).toLocaleDateString();

    const mdContent = `# ${projectTitle}
**Date:** ${date}
**Risk Level:** ${riskLevel}
**Effort Estimate:** ${effort}

---

## 1. Executive Summary
${understanding}

## 2. Complexity Analysis
### Functional Complexity
${functionalComplexity}

### Non-Functional Constraints
${nonFunctionalConstraints}

## 3. Risk Assessment
### Justification
${riskJustification}

### High Risk Modules
${highRiskModules.map(m => `- ${m}`).join('\n')}

## 4. Technical Strategy
### Architecture Pattern
${architectureRecommendation}

### Technology Stack
${techStack.map(t => `- ${t}`).join('\n')}

## 5. Quality & Automation
### Automation Strategy
${automationStrategy}

### Quality Gates
${qualityGates.map(g => `- [ ] ${g}`).join('\n')}

## 6. Final Recommendations
${finalRecommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
*Generated by DeliveryGuard AI*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectTitle.replace(/\s+/g, '_')}_Analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto py-8 px-4 space-y-8 animate-fade-in">
      
      {/* Action Toolbar */}
      <div className="flex flex-col sm:flex-row justify-end gap-3 no-print">
         <button 
           onClick={downloadMarkdown}
           className="flex items-center justify-center space-x-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 hover:text-blue-600 transition-colors shadow-sm"
         >
           <FileText className="w-4 h-4" />
           <span>Markdown</span>
         </button>
         <button 
           onClick={handlePrint}
           className="flex items-center justify-center space-x-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium text-slate-700 hover:bg-slate-50 hover:text-blue-600 transition-colors shadow-sm"
         >
           <Printer className="w-4 h-4" />
           <span>Print</span>
         </button>
         <button 
           onClick={handleExportPDF}
           className="flex items-center justify-center space-x-2 px-4 py-2 bg-blue-600 border border-blue-600 rounded-lg text-sm font-medium text-white hover:bg-blue-700 transition-colors shadow-sm"
         >
           <Download className="w-4 h-4" />
           <span>Export PDF</span>
         </button>
      </div>

      <div id="report-content" className="space-y-8">
        {/* Header Section */}
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-200 flex flex-col md:flex-row md:items-start justify-between gap-6">
          <div>
            <div className="flex items-center space-x-3 mb-2">
              <h1 className="text-3xl font-bold text-slate-900">{result.projectTitle}</h1>
              <span className={`px-3 py-1 rounded-full text-sm font-bold border uppercase ${getRiskColor(result.riskLevel)}`}>
                {result.riskLevel} Risk
              </span>
            </div>
            <p className="text-slate-600 max-w-2xl">{result.understanding}</p>
          </div>
          <div className="flex flex-col items-center">
              <span className="text-xs font-semibold uppercase text-slate-500 mb-2">Effort Estimate</span>
              <div className={`text-xl font-bold px-4 py-2 rounded-lg border bg-slate-50 text-slate-800`}>
                  {result.effort}
              </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Left Column: Complexity & Risk */}
          <div className="lg:col-span-2 space-y-8">
              
            {/* Complexity Analysis */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden break-inside-avoid">
              <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center space-x-2">
                <BrainCircuit className="w-5 h-5 text-blue-600" />
                <h2 className="font-semibold text-slate-800">Complexity Analysis</h2>
              </div>
              <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h3 className="text-sm font-bold text-slate-700 uppercase mb-2">Functional</h3>
                  <p className="text-sm text-slate-600 leading-relaxed">{result.functionalComplexity}</p>
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-700 uppercase mb-2">Non-Functional</h3>
                  <p className="text-sm text-slate-600 leading-relaxed">{result.nonFunctionalConstraints}</p>
                </div>
              </div>
            </div>

            {/* Risk Assessment */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden break-inside-avoid">
              <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center space-x-2">
                <ShieldAlert className="w-5 h-5 text-orange-600" />
                <h2 className="font-semibold text-slate-800">Risk Assessment</h2>
              </div>
              <div className="p-6">
                <div className="mb-6 p-4 bg-orange-50 rounded-lg border border-orange-100">
                  <h3 className="text-sm font-bold text-orange-900 mb-1">Justification</h3>
                  <p className="text-sm text-orange-800">{result.riskJustification}</p>
                </div>
                
                <h3 className="text-sm font-bold text-slate-700 mb-3 flex items-center">
                  <AlertOctagon className="w-4 h-4 mr-2 text-red-500" />
                  High Risk Modules
                </h3>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {result.highRiskModules.map((module, idx) => (
                    <li key={idx} className="flex items-start space-x-2 text-sm text-slate-600 bg-slate-50 p-2 rounded border border-slate-100">
                      <span className="w-1.5 h-1.5 mt-1.5 rounded-full bg-red-400 shrink-0" />
                      <span>{module}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Architecture & Tech Stack */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden break-inside-avoid">
              <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center space-x-2">
                <Layers className="w-5 h-5 text-indigo-600" />
                <h2 className="font-semibold text-slate-800">Architecture & Tech Stack</h2>
              </div>
              <div className="p-6 space-y-6">
                <div>
                  <h3 className="text-sm font-bold text-slate-700 mb-2">Architecture Pattern</h3>
                  <p className="text-sm text-slate-600">{result.architectureRecommendation}</p>
                </div>
                <div>
                  <h3 className="text-sm font-bold text-slate-700 mb-3">Recommended Stack</h3>
                  <div className="flex flex-wrap gap-2">
                    {result.techStack.map((tech, idx) => (
                      <span key={idx} className="px-3 py-1 bg-indigo-50 text-indigo-700 text-xs font-semibold rounded-full border border-indigo-100">
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>

          </div>

          {/* Right Column: Stats & Strategy */}
          <div className="space-y-8">

            {/* Visualization Card */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden p-6 break-inside-avoid">
              <h3 className="text-xs font-bold uppercase text-slate-500 mb-4 text-center">Estimations Visualized</h3>
              
              <div className="h-40 w-full mb-6 relative">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                      <Pie
                        data={riskData}
                        cx="50%"
                        cy="50%"
                        innerRadius={40}
                        outerRadius={60}
                        startAngle={180}
                        endAngle={0}
                        paddingAngle={5}
                        dataKey="value"
                      >
                        <Cell fill={result.riskLevel === RiskLevel.CRITICAL ? '#ef4444' : result.riskLevel === RiskLevel.HIGH ? '#f97316' : result.riskLevel === RiskLevel.MEDIUM ? '#eab308' : '#22c55e'} />
                        <Cell fill="#f1f5f9" />
                      </Pie>
                      <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
                <div className="absolute top-[60%] left-0 right-0 text-center">
                    <div className="text-xs text-slate-400 font-medium">Risk Score</div>
                    <div className="font-bold text-slate-700">{riskValue}%</div>
                </div>
              </div>

              <div className="h-40 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={effortData} layout="vertical" margin={{top:0, left: 30, right: 10, bottom: 0}}>
                    <XAxis type="number" hide />
                    <YAxis dataKey="name" type="category" tick={{fontSize: 12}} width={50} />
                    <Tooltip cursor={{fill: 'transparent'}} />
                    <Bar dataKey="value" radius={[0, 4, 4, 0]} barSize={20}>
                        {effortData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.name.toUpperCase() === result.effort.toUpperCase() ? getEffortColor(result.effort) : '#e2e8f0'} />
                        ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Strategy */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden break-inside-avoid">
              <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center space-x-2">
                <CheckSquare className="w-5 h-5 text-emerald-600" />
                <h2 className="font-semibold text-slate-800">Quality & Automation</h2>
              </div>
              <div className="p-6 space-y-6">
                <div>
                  <h3 className="text-xs font-bold uppercase text-slate-500 mb-2 flex items-center">
                      <Rocket className="w-3 h-3 mr-1" /> Automation
                  </h3>
                  <p className="text-sm text-slate-600">{result.automationStrategy}</p>
                </div>
                <div>
                  <h3 className="text-xs font-bold uppercase text-slate-500 mb-2 flex items-center">
                      <Code className="w-3 h-3 mr-1" /> Quality Gates
                  </h3>
                  <ul className="space-y-2">
                    {result.qualityGates.map((gate, idx) => (
                      <li key={idx} className="flex items-start text-sm text-slate-600">
                        <span className="w-1.5 h-1.5 mt-1.5 rounded-full bg-emerald-400 shrink-0 mr-2" />
                        {gate}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

          </div>
        </div>
        
        {/* Final Recommendations */}
        <div className="bg-gradient-to-r from-slate-800 to-slate-900 rounded-xl shadow-lg text-white p-8 break-inside-avoid">
          <h2 className="text-xl font-bold mb-4 flex items-center">
              <Clock className="w-5 h-5 mr-2 text-blue-400" />
              Final Delivery Recommendations
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {result.finalRecommendations.map((rec, idx) => (
                  <div key={idx} className="bg-white/10 p-4 rounded-lg border border-white/5 backdrop-blur-sm">
                      <div className="font-mono text-2xl text-blue-400/20 mb-2 font-bold absolute top-2 right-4 pointer-events-none">
                          0{idx + 1}
                      </div>
                      <p className="text-sm text-slate-200 relative z-10">{rec}</p>
                  </div>
              ))}
          </div>
        </div>
      </div>
    </div>
  );
};